// api/beehiiv-webhook.js
// Receives webhook events from beehiiv when a subscription is created.
// Purpose: catch subscribers who came in through "native beehiiv paths" —
// Boosts, Recommendations, Referrals, organic beehiiv signups — and sync
// them into Resend so they (a) receive the Boost welcome email with the
// Vault link and (b) exist in the Resend audience for future transactional sends.
//
// Subscribers who originated from /api/subscribe (readmason.com forms) are
// already in Resend — those are detected via utm_source === 'readmason.com'
// and skipped.
//
// Required environment variables (set in Vercel dashboard):
//   - RESEND_API_KEY            (existing)
//   - RESEND_SEGMENT_ID         (existing)
//   - BEEHIIV_WEBHOOK_SECRET    (new — generated by beehiiv on webhook creation)
//   - ALERT_EMAIL               (new — Cherwin's email for sync failure alerts)

import crypto from 'crypto';

// ─────────────────────────────────────────────────────────
// Boost / Recommendation welcome email — sent when a subscriber arrives
// via a non-readmason.com path (Boost partner, Recommendation, Referral,
// or organic beehiiv signup). Different from the standard newsletter
// welcome because we lead with the free Vault as a thank-you gift.
// Matches the masthead/footer system of VAULT_WELCOME_HTML.
// ─────────────────────────────────────────────────────────
const BOOST_WELCOME_HTML = `<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="x-apple-disable-message-reformatting" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="color-scheme" content="light only" />
<meta name="supported-color-schemes" content="light only" />
<title>Welcome to Mason \u2014 here's a free book</title>
<style type="text/css">
@import url('https://fonts.googleapis.com/css2?family=Geist:wght@400;500;600;700&family=Geist+Mono:wght@400;500;700&display=swap');
body, table, td, a { -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; }
table, td { mso-table-lspace: 0pt; mso-table-rspace: 0pt; }
img { -ms-interpolation-mode: bicubic; border: 0; height: auto; line-height: 100%; outline: none; text-decoration: none; }
body { margin: 0 !important; padding: 0 !important; width: 100% !important; background-color: #EEE7D2 !important; }
table { border-collapse: collapse; }
@media only screen and (max-width: 600px) {
  .container { width: 100% !important; }
  .padding-outer { padding-left: 24px !important; padding-right: 24px !important; }
  .headline { font-size: 30px !important; line-height: 1.15 !important; }
  .cta-btn { display: block !important; width: 100% !important; text-align: center !important; box-sizing: border-box; }
}
</style>
</head>
<body style="margin:0;padding:0;background-color:#EEE7D2;font-family:'Geist','Helvetica Neue',Arial,sans-serif;">
<div style="background-color:#EEE7D2;background-image:radial-gradient(circle at 1px 1px, rgba(10,10,10,0.08) 1px, transparent 0);background-size:16px 16px;padding:40px 0;">
<table role="presentation" class="container" width="600" border="0" cellspacing="0" cellpadding="0" align="center" style="width:600px;max-width:600px;background-color:#EEE7D2;">

<!-- Masthead -->
<tr>
<td class="padding-outer" style="padding:0 40px;">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td style="background:#0A0A0A;padding:28px 32px;border-left:6px solid #C64728;">
<table width="100%" border="0" cellspacing="0" cellpadding="0">
<tr>
<td style="font-family:'Geist','Helvetica Neue',Arial,sans-serif;font-size:28px;font-weight:700;letter-spacing:-0.02em;color:#FAFAF7;">Mason<span style="color:#C64728;">.</span></td>
<td align="right" style="font-family:'Geist Mono','JetBrains Mono',monospace;font-size:10px;color:#C64728;letter-spacing:0.25em;text-transform:uppercase;font-weight:700;">Welcome</td>
</tr>
</table>
</td>
</tr>
</table>
</td>
</tr>

<!-- Spacer -->
<tr><td style="height:48px;line-height:48px;">&nbsp;</td></tr>

<!-- Label -->
<tr>
<td class="padding-outer" style="padding:0 40px;">
<div style="font-family:'Geist Mono','JetBrains Mono',monospace;font-size:10px;color:#C64728;letter-spacing:0.3em;text-transform:uppercase;font-weight:700;margin-bottom:20px;">A gift, on the house</div>
</td>
</tr>

<!-- Headline -->
<tr>
<td class="padding-outer" style="padding:0 40px;">
<h1 class="headline" style="font-family:'Geist','Helvetica Neue',Arial,sans-serif;font-size:38px;line-height:1.1;letter-spacing:-0.025em;color:#0A0A0A;font-weight:700;margin:0 0 24px 0;">Welcome to Mason. Here's a free book.</h1>
</td>
</tr>

<!-- Body -->
<tr>
<td class="padding-outer" style="padding:0 40px;">
<div style="font-family:'Geist','Helvetica Neue',Arial,sans-serif;font-size:16px;line-height:1.65;color:#0A0A0A;font-weight:400;">

<p style="margin:0 0 20px 0;">Hey \u2014</p>

<p style="margin:0 0 24px 0;">You just subscribed to Mason through another newsletter. Welcome \u2014 glad you're here.</p>

<p style="margin:0 0 28px 0;">As a thank-you for jumping in, here's a free 89-page book we made: <strong>The Prompt Vault</strong>. 28 production prompts from teams shipping AI at scale. Every one cited, every one with a "what breaks" note.</p>

<!-- CTA button -->
<table role="presentation" width="100%" border="0" cellspacing="0" cellpadding="0" style="margin:0 0 32px 0;">
<tr>
<td>
<a href="https://readmason.com/vault.pdf" class="cta-btn" style="display:inline-block;background:#C64728;color:#FAFAF7;font-family:'Geist','Helvetica Neue',Arial,sans-serif;font-size:15px;font-weight:600;letter-spacing:0.02em;text-decoration:none;padding:16px 28px;border-left:4px solid #0A0A0A;">Download the Vault \u2192</a>
</td>
</tr>
</table>

<p style="margin:0 0 20px 0;font-family:'Geist Mono','JetBrains Mono',monospace;font-size:11px;color:#6A6A6A;letter-spacing:0.15em;text-transform:uppercase;">What you signed up for</p>

<p style="margin:0 0 20px 0;"><strong style="color:#0A0A0A;">Monday \u00b7 The Build.</strong> One AI system, shown end-to-end. The story, the stack, the prompt, what broke. Named builders, real sources, honest failure modes.</p>

<p style="margin:0 0 20px 0;"><strong style="color:#0A0A0A;">Thursday \u00b7 The Move.</strong> One pattern worth stealing. The architectural shift, not the tool launch. When to make the move, when not to.</p>

<p style="margin:0 0 20px 0;">No press releases. No listicles. No "this changes everything." Just real people, real systems, real detail \u2014 twice a week.</p>

<p style="margin:0 0 20px 0;">If Mason isn't what you expected, the unsubscribe link is at the bottom of every issue. The book is yours either way.</p>

<p style="margin:32px 0 0 0;font-family:'Geist Mono','JetBrains Mono',monospace;font-size:12px;color:#0A0A0A;letter-spacing:0.2em;text-transform:uppercase;font-weight:700;">\u2014 Mason</p>

</div>
</td>
</tr>

<!-- Spacer -->
<tr><td style="height:56px;line-height:56px;">&nbsp;</td></tr>

<!-- Footer -->
<tr>
<td class="padding-outer" style="padding:0 40px 40px 40px;border-top:1px solid rgba(10,10,10,0.12);padding-top:24px;">
<div style="font-family:'Geist Mono','JetBrains Mono',monospace;font-size:10px;color:#666;letter-spacing:0.15em;line-height:1.8;text-transform:uppercase;">
You're receiving this because you subscribed to Mason via a partner newsletter recommendation.<br/>
<a href="{{{RESEND_UNSUBSCRIBE_URL}}}" style="color:#666;border-bottom:1px solid #999;text-decoration:none;">Unsubscribe</a> &nbsp;\u00b7&nbsp; <a href="https://readmason.com" style="color:#666;border-bottom:1px solid #999;text-decoration:none;">readmason.com</a>
</div>
</td>
</tr>

</table>
</div>
</body>
</html>`;

// ─────────────────────────────────────────────────────────
// In-memory rolling failure tracker for alert throttling.
// Persists for the lifetime of a warm Vercel lambda (~15 min idle).
// Cold start resets it. Accept this — for Mason's volume the trade-off
// is right. Swap to Upstash Redis if alert reliability becomes critical.
// ─────────────────────────────────────────────────────────
const failureLog = []; // array of timestamps (ms) within last hour
let lastAlertSentAt = 0;
const ONE_HOUR_MS = 60 * 60 * 1000;
const FAILURE_THRESHOLD = 3;

function recordFailureAndMaybeAlert(context) {
  const now = Date.now();
  // Prune entries older than 1 hour
  while (failureLog.length && now - failureLog[0] > ONE_HOUR_MS) {
    failureLog.shift();
  }
  failureLog.push(now);

  if (failureLog.length >= FAILURE_THRESHOLD && now - lastAlertSentAt > ONE_HOUR_MS) {
    lastAlertSentAt = now;
    // Fire and forget — don't block webhook response on alert delivery
    sendFailureAlert(failureLog.length, context).catch(err => {
      console.error('Alert email failed to send:', err);
    });
  }
}

async function sendFailureAlert(count, context) {
  const apiKey = process.env.RESEND_API_KEY;
  const alertTo = process.env.ALERT_EMAIL;
  if (!apiKey || !alertTo) {
    console.error('Cannot send alert — missing RESEND_API_KEY or ALERT_EMAIL');
    return;
  }

  const body = `Mason beehiiv \u2192 Resend sync has logged ${count} failures in the past hour.

Latest failure context:
${JSON.stringify(context, null, 2)}

Check Vercel logs for the full picture:
https://vercel.com/dashboard \u2192 readmason \u2192 Logs \u2192 /api/beehiiv-webhook

This alert is throttled to once per hour.`;

  await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Mason Alerts <newsletter@readmason.com>',
      to: [alertTo],
      subject: `Mason sync alert: ${count} failures in past hour`,
      text: body,
    }),
  });
}

// ─────────────────────────────────────────────────────────
// Verify beehiiv webhook signature.
// beehiiv signs requests using HMAC-SHA256 with the webhook secret.
// The signature is delivered via the `svix-signature` header (beehiiv uses
// Svix as their webhook delivery layer). If the header shape changes, log
// the raw headers on the first hit and we'll tighten this.
// ─────────────────────────────────────────────────────────
function verifyBeehiivSignature(req, rawBody) {
  const secret = process.env.BEEHIIV_WEBHOOK_SECRET;
  if (!secret) {
    console.error('BEEHIIV_WEBHOOK_SECRET not set');
    return false;
  }

  const svixId = req.headers['svix-id'];
  const svixTimestamp = req.headers['svix-timestamp'];
  const svixSignature = req.headers['svix-signature'];

  if (!svixId || !svixTimestamp || !svixSignature) {
    console.warn('Missing svix-* headers — rejecting');
    return false;
  }

  // Svix signs: `${svix_id}.${svix_timestamp}.${body}`
  // Secret is base64-encoded, prefixed with "whsec_"
  try {
    const secretBytes = Buffer.from(secret.replace(/^whsec_/, ''), 'base64');
    const signedPayload = `${svixId}.${svixTimestamp}.${rawBody}`;
    const expected = crypto
      .createHmac('sha256', secretBytes)
      .update(signedPayload)
      .digest('base64');

    // svixSignature is space-separated list like "v1,abc123 v1,def456"
    // Any signature matching is sufficient (Svix rotates them)
    const sigs = svixSignature.split(' ').map(s => s.split(',')[1]);
    return sigs.some(sig => {
      try {
        return crypto.timingSafeEqual(
          Buffer.from(sig, 'base64'),
          Buffer.from(expected, 'base64')
        );
      } catch {
        return false;
      }
    });
  } catch (err) {
    console.error('Signature verification threw:', err);
    return false;
  }
}

// ─────────────────────────────────────────────────────────
// Check if a contact already exists in Resend.
// Returns: { exists: bool, error: optional }
// ─────────────────────────────────────────────────────────
async function resendContactExists(email) {
  const apiKey = process.env.RESEND_API_KEY;
  const segmentId = process.env.RESEND_SEGMENT_ID;
  try {
    const r = await fetch(
      `https://api.resend.com/audiences/${segmentId}/contacts/${encodeURIComponent(email)}`,
      {
        method: 'GET',
        headers: { 'Authorization': `Bearer ${apiKey}` },
      }
    );
    if (r.ok) return { exists: true };
    if (r.status === 404) return { exists: false };
    // Some other error — treat as not-exists but log it
    const txt = await r.text();
    console.warn('Resend contact lookup non-200:', r.status, txt);
    return { exists: false, error: `${r.status} ${txt}` };
  } catch (err) {
    console.error('Resend contact lookup threw:', err);
    return { exists: false, error: err.message };
  }
}

// ─────────────────────────────────────────────────────────
// Add a contact to the Resend segment.
// Mirrors the schema used in /api/subscribe.js — only fields Resend's
// audience properties schema actually accepts.
// ─────────────────────────────────────────────────────────
async function addToResend(email, sourceLabel) {
  const apiKey = process.env.RESEND_API_KEY;
  const segmentId = process.env.RESEND_SEGMENT_ID;

  const r = await fetch('https://api.resend.com/contacts', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      email,
      unsubscribed: false,
      segments: [{ id: segmentId }],
      // NOTE: Resend rejects arbitrary properties (422). Stick to the same
      // fields /api/subscribe.js uses. We encode the source into `industry`
      // as a temporary tag carrier — re-evaluate if Resend adds tag support.
      properties: {
        role: '',
        company_size: '',
        industry: `beehiiv:${sourceLabel}`,
        country: '',
      },
    }),
  });

  if (!r.ok) {
    const errText = await r.text();
    throw new Error(`Resend contact create failed: ${r.status} ${errText}`);
  }
  return true;
}

// ─────────────────────────────────────────────────────────
// Send the Boost welcome email via Resend.
// ─────────────────────────────────────────────────────────
async function sendBoostWelcomeEmail(email) {
  const apiKey = process.env.RESEND_API_KEY;
  const r = await fetch('https://api.resend.com/emails', {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${apiKey}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      from: 'Mason <newsletter@readmason.com>',
      to: [email],
      reply_to: 'newsletter@readmason.com',
      subject: "Welcome to Mason \u2014 here's a free book",
      html: BOOST_WELCOME_HTML,
    }),
  });
  if (!r.ok) {
    const errText = await r.text();
    throw new Error(`Resend email send failed: ${r.status} ${errText}`);
  }
  return true;
}

// ─────────────────────────────────────────────────────────
// Read raw body — required for signature verification because Vercel's
// default JSON parser strips the original bytes used in the HMAC.
// ─────────────────────────────────────────────────────────
export const config = {
  api: {
    bodyParser: false,
  },
};

async function readRawBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', c => chunks.push(c));
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')));
    req.on('error', reject);
  });
}

// ─────────────────────────────────────────────────────────
// Main handler
// ─────────────────────────────────────────────────────────
export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  let rawBody;
  try {
    rawBody = await readRawBody(req);
  } catch (err) {
    console.error('Failed to read request body:', err);
    return res.status(400).json({ error: 'Bad request body' });
  }

  // Signature verification
  if (!verifyBeehiivSignature(req, rawBody)) {
    console.warn('Invalid webhook signature — rejecting');
    return res.status(401).json({ error: 'Invalid signature' });
  }

  let payload;
  try {
    payload = JSON.parse(rawBody);
  } catch (err) {
    console.error('Failed to parse webhook JSON:', err);
    return res.status(400).json({ error: 'Invalid JSON' });
  }

  // Log every webhook hit at least once so we can see the shape beehiiv
  // is sending. Remove or downgrade to debug after first prod payloads.
  console.log('beehiiv webhook received:', JSON.stringify(payload).slice(0, 1000));

  // beehiiv wraps events as: { event_type, id, created, data: { ... } }
  // We defend against both wrapped and flat shapes.
  const eventType = payload.event_type || payload.type;
  const data = payload.data || payload;

  // Only act on subscription creation events.
  // Accept several known event-type strings to be tolerant of doc drift.
  const isCreateEvent = !eventType
    || /subscription[._-]?created/i.test(eventType)
    || /subscriber[._-]?created/i.test(eventType);
  if (!isCreateEvent) {
    console.log('Ignoring non-create event:', eventType);
    return res.status(200).json({ status: 'ignored', reason: 'not a create event' });
  }

  const email = (data.email || '').toLowerCase().trim();
  if (!email || !email.includes('@')) {
    console.warn('Webhook missing valid email:', data);
    return res.status(200).json({ status: 'skipped', reason: 'no email' });
  }

  // Detect "this came from /api/subscribe" — those subs are already in Resend.
  // /api/subscribe.js sets utm_source: 'readmason.com' on every beehiiv write.
  const utmSource = data.utm_source || '';
  const utmCampaign = data.utm_campaign || '';
  const referringSite = data.referring_site || '';
  const cameFromOurForm =
    utmSource === 'readmason.com' ||
    referringSite === 'https://readmason.com' ||
    referringSite === 'readmason.com';

  if (cameFromOurForm) {
    return res.status(200).json({ status: 'skipped', reason: 'originated from /api/subscribe' });
  }

  // Build a human-readable source label for tagging in Resend.
  // beehiiv typically populates one of: subscription_premium_tier_changes,
  // boosts, recommendations, referrals, or organic.
  const sourceLabel =
    data.source ||
    data.subscription_source ||
    utmSource ||
    utmCampaign ||
    'beehiiv-native';

  // Dedup check — don't double-write or re-welcome.
  const dedup = await resendContactExists(email);
  if (dedup.exists) {
    return res.status(200).json({ status: 'skipped', reason: 'already in Resend' });
  }

  // Write to Resend + send welcome.
  try {
    await addToResend(email, sourceLabel);
  } catch (err) {
    console.error('addToResend failed:', err.message);
    recordFailureAndMaybeAlert({ stage: 'addToResend', email, source: sourceLabel, err: err.message });
    // Graceful degradation: return 200 so beehiiv doesn't retry forever.
    return res.status(200).json({ status: 'error', stage: 'resend-add', error: err.message });
  }

  try {
    await sendBoostWelcomeEmail(email);
  } catch (err) {
    console.error('sendBoostWelcomeEmail failed:', err.message);
    recordFailureAndMaybeAlert({ stage: 'sendBoostWelcomeEmail', email, source: sourceLabel, err: err.message });
    return res.status(200).json({ status: 'error', stage: 'welcome-email', error: err.message });
  }

  console.log('beehiiv sync OK:', email, 'source:', sourceLabel);
  return res.status(200).json({ status: 'synced', email, source: sourceLabel });
}
